### ISSUE TITLE
Landing page dashboard

### ISSUE THREAD

**Issue by wimhugo** [SAEONData/NCCRD#15]
- [ ] 1. Data source(s) as JSON services
- [ ] 2. Potentially a combination of data visualisations (say 4 sections) depicting different summary views
- [ ] 2.1 Mitigation and Adaptation by top level Sector (say 2 ringed pie charts)
- [ ] 2.2 Mitigation and Adaptation by Province (same)
- [ ] 2.3 Research Entries per Sector
- [ ] 2.4 Funding Opportunities per Sector

In time, link each view to a detail page with an extra level of detail (second level sector, DM instead of province)

Asana: https://app.asana.com/0/660264284498429/681174572404635/f

**Comment by andre-engelbrecht** [comment]
Obsolete. Rpleaced by new task
