### ISSUE TITLE
MAOptions

### ISSUE THREAD

**Issue by andre-engelbrecht** [SAEONData/NCCRD#16]
There is still some clarity as to what to do regarding this part of the data.
This needs to be discussed with Wim to be finalized

Asana: https://app.asana.com/0/660264284498429/681174572404631/f

**Comment by Andre-SAEON** [comment]
Awaiting data from Wim.

Note: Provisioned tables for MAOptions and associated data will fall away and the new data will slot into the ResearchDetails table under a new project type/status.

**Comment by andre-engelbrecht** [comment]
Closed until re-requested at a later stage.
