### ISSUE TITLE
Disconnect between DB-Users and SSO-Users

### ISSUE THREAD

**Issue by andre-engelbrecht** [SAEONData/NCCRD#53]
NCCRD already has a list of user accounts, that cannot be ported to the IdentityService. This creates a disconnect. The user accounts from the database are used as lookup data for project-managers, thus we can't just throw them out.

I suggest we convert the existing user accounts into a simpler project-managers lookup table that can be managed same as any of our other lists. These "users" are then no longer users, but rather just a list of names with associated data. And these names are not directly linked to actual user accounts on the IdentityService.

https://app.asana.com/0/660264284498429/681174572404651/f

**Comment by Andre-SAEON** [comment]
Pending discussions with DEA

**Comment by andre-engelbrecht** [comment]
Converted to lookup table
